### PR TITLE
Update _helpers.py

### PR DESCRIPTION
**Pull request by watsy0007**
socks5h & socks4a

### CODE REVIEW

**Comment by romis2012** [comment]
It doesn't make any sense, just use `socks4` and `socks5`

**Comment by watsy0007** [comment]
socks4 and socks4 resolve hostname locally
for some reason (eg. china),  hostname has been blocked. proxy failed . 
socks5h and socks4a resolve hostname by socks server.

**Comment by romis2012** [comment]
> ...resolve hostname...

Use  `rdns` (which means "remote resolve") argument

**Comment by PaTTeeL** [comment]
> > ...resolve hostname...
> 
> Use `rdns` (which means "remote resolve") argument

Can we make 'rdns' automatically enabled by using prefix socks4a:// ? 
And is it possible to have a compatible scheme socks5h:// for some scripts?

**Comment by romis2012** [comment]
> Can we make 'rdns' automatically enabled by using prefix socks4a:// ?

No. You should pass rdns argument explicitly (for socks4 proxy it is False by default)

> And is it possible to have a compatible scheme socks5h:// for some scripts?

Use `socks5` scheme, for socks5 proxies rdns=True by default

**Comment by PaTTeeL** [comment]
> > Can we make 'rdns' automatically enabled by using prefix socks4a:// ?
> 
> No. You should pass rdns argument explicitly (for socks4 proxy it is False by default)
> 
So could it possible to have a easy way that using socks4:// for local resolve and socks4a:// for remote resolve?

> > And is it possible to have a compatible scheme socks5h:// for some scripts?
> 
> Use `socks5` scheme, for socks5 proxies rdns=True by default

Sorry for edit.
Some commands like curl use local resolve with socks5:// which socks5h:// for remote. It's great to have a compatible scheme to guarantee remote resolving for the entire environment.

**Comment by romis2012** [comment]
> So could it possible to have a easy way that using socks4:// for local resolve and socks4a:// for remote resolve?

> Sorry for edit.
Some commands like curl use local resolve with socks5:// which socks5h:// for remote. It's great to have a compatible scheme to guarantee remote resolving for the entire environment.

Everything is described above. Use `socks4`/`socks5` scheme and `rdns` parameter for remote resolve.

**Pull request closed without merging**
